services:
  job-board-ai-next:
    container_name: job-board-ai-next
    restart: always
    image: node:20.11.0
    ports: 
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/jobBoardAi-next
    working_dir: /usr/src/jobBoardAi-next
    networks:
      - client-network

    command:
