services:
  job-board-ai-next:
    container_name: job-board-ai-next
    restart: always
    image: node:20.11.0
    ports: 
      - 4000:3010
    environment:
      - PORT=3010
      - NEXT_PUBLIC_API_URL=http://212.85.27.30:4001
      - NEXT_PUBLIC_GRAPHQL_URL=http://212.85.27.30:4001/graphql
      - NEXT_PUBLIC_WS_URL=ws://212.85.27.30:4001
      - NEXT_PUBLIC_BATCH_URL=http://212.85.27.30:4002
    volumes:
      - ./:/usr/src/jobBoardAi-next
    working_dir: /usr/src/jobBoardAi-next
    networks:
      - client-network

    command: bash -c "yarn install && yarn build && yarn run start"

networks:
  client-network:
    driver: bridge
